AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Metrics/MethodLength:
  Max: 5

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/LineLength:
  Max: 20

Metrics/AbcSize:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Max: 5
