config_version = "0"

exclude_patterns = [
  # Debug binaries
  "**/__debug_bin",

  # Test coverage and CI artifacts
  "**/c.out",
  "**/junit.xml",

  # Temporary files
  "**/tmp/**",
  "**/git_clones/**",
]

test_patterns = [
  "**/testdata/**",
  "**/testhelper/**",
  "**/*_test.go",
  "**/*_mock.go",
  "**/*mock*/**",
]

[smells]
mode = "comment"

[[source]]
name = "default"
default = true


[[plugin]]
name = "ruff"
drivers = [
  "lint",
]

[[plugin]]
name = "coffeelint"
mode = "monitor"
[plugins.definitions.coffeelint]
config_files = ["coffeelint.json"]
exported_config_paths = ["coffeelint.json"]

[[plugin]]
name = "rubocop"
[plugins.definitions.rubocop]
config_files = [".rubocop.yml"]
exported_config_paths = [".rubocop.yml"]

[[plugin]]
name = "prettier"
[plugins.definitions.prettier]
config_files = [".prettierrc"]
exported_config_paths = [".prettierrc"]
